#!/bin/sh

bin_name="alphabet"

tmp="$0"
tmp="$(dirname "$tmp")"
tmp="$(dirname "$tmp")"
bundle="$(dirname "$tmp")"

export GTK_THEME=macOS-Dark-6.1-dark

exec "$bundle/Contents/MacOs/$bin_name-bin" "$@"
